### PR TITLE
Fix required parameters deprecation warning

### PR DESCRIPTION
**Pull request by KacerCZ**
Fixes "Required parameter $prefix follows optional parameter $configs"

### CODE REVIEW

**Comment by KacerCZ** [comment]
@BafS Please review this PR. It fixes deprecation under PHP 8.0.

**Comment by BafS** [comment]
Thanks for the fix !

**Comment by pableu** [comment]
Are you going to tag a version with this?

**Comment by BafS** [comment]
Done, v3.4.2

**Pull request merged**
